### ISSUE TITLE
Some advice

### ISSUE THREAD

**Issue by qwesdfok** [tfg13/LanXchange#4]
File names could be chinese. So the UTF-8 encoding is more suitable? JFileChooser is not bad.
By the way, it is useful!

**Comment by tfg13** [comment]
Filenames should already be UTF-8 encoded and support all kinds of characters. Is there a problem with special chars somewhere specific?

**Comment by tfg13** [comment]
Ah, the included font is missing lots of characters. Transfers should still work, though.
I will look into it

**Comment by tfg13** [comment]
Ok, so the problem is the included font. I implemented a quick fix: If the filename contains chars that are not available, LanXchange now tries to use a system-supplied font to render the file name.

I tested this with some randomly copied chinese chars from wikipedia and it worked, but it would be best if someone who is really affected by this tried my fix.

So it would be great if you could download the new .jar file from here https://github.com/tfg13/LanXchange/releases/tag/untagged-009b903c8e9dc7d0f0dd
Just copy it into the LanXchange folder and overwrite the old file there.
Then try again and report back if the problem is fixed.

**Comment by qwesdfok** [comment]
The URL you gave cant not be opened. "404 Not Found" appears. Did you forget to commit new .jar file?

**Comment by qwesdfok** [comment]
So I downloaded the source and compiled it. It worked correctly. You can commit this version to /releases/stable directly. Thanks a lot!

**Comment by tfg13** [comment]
Updated version is out.
Thanks for reporting this and testing the fix!
