### ISSUE TITLE
Choose download location on Android

### ISSUE THREAD

**Issue by aronovgj** [tfg13/LanXchange#6]
That app is awesome. I like how minimalistic it is. 

A nice addition would be to be able to choose the download location in Android. The PC version already does that.

**Comment by tfg13** [comment]
Yup, I postponed this feature until someone actually needs it.
Guess that just happend :)

Do you need to be able to select SD-cards as a download location as well?
Because adding a location chooser for the internal storage is quite easy, but dealing with SD cards became more and more complicated with each new version of android, so this would delay this feature even more.

That being said, I am super busy right now, not sure how fast I can look into this.

**Comment by aronovgj** [comment]
I know that SD-cards are problematic and I personally don't need that.

**Comment by tfg13** [comment]
This should be implemented now (minus SD card).
Will build and upload a new android build soon(TM).
