### ISSUE TITLE
No way to cancel file transfer in Android app

### ISSUE THREAD

**Issue by aronovgj** [tfg13/LanXchange#8]
:)

**Comment by tfg13** [comment]
Yup, this is mostly the android version lagging behind the PC version, especially in the UI department.
The functionality is there, it is just not exposed because I find it difficult to create a good UI for it.
For the same reason, the android version currently does not display uploads, which can also be a bit confusing for new users.

**Comment by aronovgj** [comment]
a) Give the icon on the left (arrow down) a function. Make it a toggle, as in `green arrow` means download and `red trash bin` means cancel.

b) Make it swipable. Swipe to the left/right cancels the download

c) Add another icon to the right (a trashbin) to cancel

I like the first one. Swiping away an entry would be nice to remove a finished download from the list. (another enhancement :) )

**Comment by tfg13** [comment]
I'll let you in on a little secret: You can "long-click" entries (hold) in order to remove them.
This is semi-hidden, because it is advanced functionality: If the file is still available, the entry stays there to allow re-downloads. If the file is gone, the entry disappears.
The PC version does the same on a right click.

**Comment by aronovgj** [comment]
Holding does not seem to be the most practical way but I can live with that
